#
# 이 파일은 도커를 관리하는 파일입니다. 
#
version: '2'
services:

  # withme2020 개발 실행 컨테이너 jekyll을 이용
  withme2020-jekyll-dev:
    image: jekyll/jekyll:3.8.5
    ports:
      - 5000:5000
      - 35729:35729
    volumes:
      - ${HOME}/withme2020.github.io/:/srv/jekyll
      - ${HOME}/m2pub.github.io/bundle:/usr/local/bundle
    environment:
      - LANG=ko_KR.UTF-8
      - LANGUAGE=ko_KR
      - TZ=Asia/Seoul
      - LC_ALL=ko_KR.UTF-8
    restart: unless-stopped
    command: jekyll serve

